# Site settings
title:       Jay Shah
email:       jayshahtx@gmail.com
author:      Jay Shah
description: "Personal blog and projects"
baseurl:     ""
url:         "http://jayshah.me"

# Google analytics
google_analytics: UA-63732665-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: jayshahme

# Social icons
show_social_icons: true
github_username: jayshahtx
stackoverflow_id:
twitter_username: jayshahtx
google_plus_id:
linkedin_username: jayshahtx
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Click to share this post'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true

# open graph
og_image: /assets/jayshah_circlepic.png # Default image for Open Graph tag
og_image_type: image/png
og_image_width: 300
og_image_height: 300
